#!/bin/bash
for extension in dll exe
do
	for file in $(find . -name "*.$extension" -type f) 
	do
		echo $file ;
	done
done
echo -e "\e[31mpress any char if everything ok; ctrl c otherwise\e[0m"
read

for extension in dll exe
do
        for file in $(find . -name "*.$extension" -type f)
        do
                rm -v $file
        done
done


echo "done"
